### ISSUE TITLE
Can't access TradingView's API. HTTP status code: 404.

### ISSUE THREAD

**Issue by amir-behnous** [deathlyface/tradingview-ta-demo#2]
Can't access TradingView's API. HTTP status code: 404. 
Please report this error on GitHub: deathlyface/tradingview-ta-demo and attach the screenshot of the form.

**Comment by deathlyface** [comment]
Hello @amir-behnous,

Could you please give more details? What's the symbol/interval/exchange/screener?

**Comment by amir-behnous** [comment]
my bad, i enter wrong informations

**Comment by amir-behnous** [comment]
sorry
